<?php


use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_theme().
 */
function drtest_theme(): array {
  return [
    'drtest_entity' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for drtest entity templates.
 *
 * Default template: drtest-entity.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the drtest entity information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_drtest_entity(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function drtest_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish drtest entities.
      $storage = \Drupal::entityTypeManager()->getStorage('drtest_entity');
      $drtest_entity_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($drtest_entity_ids) as $drtest_entity) {
        $drtest_entity->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize drtest entities.
      $storage = \Drupal::entityTypeManager()->getStorage('drtest_entity');
      $drtest_entity_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($drtest_entity_ids) as $drtest_entity) {
        $drtest_entity->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function drtest_user_predelete(UserInterface $account): void {
  // Delete drtest entities that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('drtest_entity');
  $drtest_entity_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($drtest_entity_ids)
  );
}

/**
 * @param EntityTypeInterface[] $entity_types
 */
function drtest_entity_type_build(&$entity_types) {
  if (isset($entity_types['node'])) {
    $entity_types['node']->setClass('Drupal\drtest\Entity\DrtestNode');
  }
}